---
sudo: required
language: python
services:
  - docker
before_install:
  - sudo apt-get -qq update
install:
  - pip install ansible
  - pip install ansible-lint
  - pip install yamllint
script:
  - bash ci-linting-checks.sh
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
