---
# tasks file for scicore-katello-register

# set var "katello_client_yum_repo_add=true" if you want to use upstream repos for foreman-client
# by default we don't add the upstream repo because we assume our katello instance will provide the foreman-client rpms
- name: Add the foreman-client yum repo
  yum:
    name: "{{ katello_client_yum_repo_rpm }}"
    state: installed
  when: katello_client_yum_repo_add

- name: install subscription-manager
  yum:
    name: subscription-manager
    state: installed

- name: install epel-release rpm to disable it afterwards
  yum:
    name: epel-release
    state: installed

- name: install the katello ca-consumer
  yum:
    name: http://{{ katello_client_katello_server_hostname }}/pub/katello-ca-consumer-latest.noarch.rpm
    disable_gpg_check: yes

- name: register the node with katello
  redhat_subscription:
    activationkey: "{{ katello_client_activationkey }}"
    org_id: "{{ katello_client_org_id }}"
    rhsm_baseurl: "{{ katello_client_rhsm_baseurl }}"
    force_register: "{{ katello_client_force_register }}"
    state: present
  notify: yum-clean-metadata

- name: Update config for default yum repos to disable them
  yum_repository:
    name: "{{ item.name }}"
    file: "{{ item.file }}"
    description: "{{ item.description | default(omit) }}"
    mirrorlist: "{{ item.mirrorlist | default(omit) }}"
    metalink: "{{ item.metalink | default(omit) }}"
    gpgcheck: "{{ item.gpgcheck | default(omit) }}"
    gpgkey: "{{ item.gpgkey | default(omit) }}"
    enabled: "{{ item.enabled }}"
  loop: "{{ katello_client_repos_to_update }}"
  notify: yum-clean-metadata

- name: Disable the yum fastest mirror plugin
  lineinfile:
    dest: /etc/yum/pluginconf.d/fastestmirror.conf
    backup: no
    regexp: "^enabled"
    line: "enabled=0"
  when: katello_client_disable_yum_fastest_mirror_plugin

# make sure we clean yum metadata after updating yum repos
- meta: flush_handlers

- name: Install katello-client packages
  yum:
    name: "{{ katello_client_extra_packages }}"
    state: installed

# katello-agent is deprecated. You probably don't want this
- name: Install katello agent (if you are not using the foreman remote-exec plugin or ansible)
  block:

    # https://theforeman.org/plugins/katello/3.15/installation/clients.html
    # https://yum.theforeman.org/client/2.0/el7/x86_64/
    - name: install katello-agent (this is provided by the katello repos)
      yum:
        name: katello-agent
        state: installed

    - name: start and enable goferd daemon
      service:
        name: goferd
        state: started
        enabled: true

  when: katello_install_agent
